tasks:
  - init: |
      npm install
      npm init -y
      npm i -D eslint babel-eslint eslint-plugin-react eslint-plugin-react-hooks
    command: |
      echo "react container initialized"
ports:
  - port: 8080
    onOpen: open-preview
